Dev
heywhereismymind/my_news_site_project pull request #3
Opened 2024-04-21 12:28 UTC by heywhereismymind

- Add debugging
- Add redis

2024-04-21 12:29 UTC, heywhereismymind commented
Не получилось почему-то с ребейсом :(

заруинил всю ветку, пришлось мержить

2024-04-23 17:32 UTC, udevgeektutor requested changes

2024-04-23 17:32 UTC, udevgeektutor commented on mywebsite/news/urls.py
> +    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
Это можно упростить до 1 слова, тогда и в шаблоне не придется писать столько букв, а лишь 1 слово)

2024-04-23 17:32 UTC, udevgeektutor commented on mywebsite/news/urls.py
> +    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
```suggestion
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='слон'),
```
хоть так

2024-04-23 17:32 UTC, udevgeektutor commented on mywebsite/news/templates/news/base.html
> +           href="{% url 'news:django.contrib.sitemaps.views.sitemap' %}">
к этому относится то что ниже про файл mywebsite/news/urls.py
```suggestion
           href="{% url 'news:слон' %}">
```

2024-04-23 17:34 UTC, udevgeektutor reviewed
ок

2024-04-23 17:34 UTC, udevgeektutor commented on mywebsite/news/urls.py
> +        name="django.contrib.sitemaps.views.sitemap",
уже писал про это

2024-04-25 16:38 UTC, udevgeektutor commented on README.md
> +```
Больше деталей. Расскажи тут о возможностях проекта, технологиях задействованных, и тп)

2024-05-04 09:29 UTC, merged